/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedContributionsRouteImport } from './routes/_authenticated/contributions'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDeliveryRouteImport } from './routes/_authenticated/delivery'
import { Route as AuthenticatedDisbursementsRouteImport } from './routes/_authenticated/disbursements'
import { Route as AuthenticatedDispensaryRouteImport } from './routes/_authenticated/dispensary'
import { Route as AuthenticatedDonationsRouteImport } from './routes/_authenticated/donations'
import { Route as AuthenticatedEateryInventoryRouteImport } from './routes/_authenticated/eatery-inventory'
import { Route as AuthenticatedEateryReportsRouteImport } from './routes/_authenticated/eatery-reports'
import { Route as AuthenticatedEaterySalesRouteImport } from './routes/_authenticated/eatery-sales'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedFinishedGoodsRouteImport } from './routes/_authenticated/finished-goods'
import { Route as AuthenticatedHousekeepingRouteImport } from './routes/_authenticated/housekeeping'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedPharmacyCheckoutRouteImport } from './routes/_authenticated/pharmacy-checkout'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedPurchasingRouteImport } from './routes/_authenticated/purchasing'
import { Route as AuthenticatedRawMaterialsRouteImport } from './routes/_authenticated/raw-materials'
import { Route as AuthenticatedReceiptsRouteImport } from './routes/_authenticated/receipts'
import { Route as AuthenticatedReconciliationRouteImport } from './routes/_authenticated/reconciliation'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedRetainersRouteImport } from './routes/_authenticated/retainers'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedTimeTrackingRouteImport } from './routes/_authenticated/time-tracking'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContributionsRoute =
  AuthenticatedContributionsRouteImport.update({
    id: '/contributions',
    path: '/contributions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeliveryRoute = AuthenticatedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDisbursementsRoute =
  AuthenticatedDisbursementsRouteImport.update({
    id: '/disbursements',
    path: '/disbursements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispensaryRoute = AuthenticatedDispensaryRouteImport.update({
  id: '/dispensary',
  path: '/dispensary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDonationsRoute = AuthenticatedDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEateryInventoryRoute =
  AuthenticatedEateryInventoryRouteImport.update({
    id: '/eatery-inventory',
    path: '/eatery-inventory',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEateryReportsRoute =
  AuthenticatedEateryReportsRouteImport.update({
    id: '/eatery-reports',
    path: '/eatery-reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEaterySalesRoute =
  AuthenticatedEaterySalesRouteImport.update({
    id: '/eatery-sales',
    path: '/eatery-sales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinishedGoodsRoute =
  AuthenticatedFinishedGoodsRouteImport.update({
    id: '/finished-goods',
    path: '/finished-goods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHousekeepingRoute =
  AuthenticatedHousekeepingRouteImport.update({
    id: '/housekeeping',
    path: '/housekeeping',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPharmacyCheckoutRoute =
  AuthenticatedPharmacyCheckoutRouteImport.update({
    id: '/pharmacy-checkout',
    path: '/pharmacy-checkout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasingRoute = AuthenticatedPurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRawMaterialsRoute =
  AuthenticatedRawMaterialsRouteImport.update({
    id: '/raw-materials',
    path: '/raw-materials',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceiptsRoute = AuthenticatedReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReconciliationRoute =
  AuthenticatedReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRetainersRoute = AuthenticatedRetainersRouteImport.update({
  id: '/retainers',
  path: '/retainers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimeTrackingRoute =
  AuthenticatedTimeTrackingRouteImport.update({
    id: '/time-tracking',
    path: '/time-tracking',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/contributions': typeof AuthenticatedContributionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/disbursements': typeof AuthenticatedDisbursementsRoute
  '/dispensary': typeof AuthenticatedDispensaryRoute
  '/donations': typeof AuthenticatedDonationsRoute
  '/eatery-inventory': typeof AuthenticatedEateryInventoryRoute
  '/eatery-reports': typeof AuthenticatedEateryReportsRoute
  '/eatery-sales': typeof AuthenticatedEaterySalesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/finished-goods': typeof AuthenticatedFinishedGoodsRoute
  '/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/members': typeof AuthenticatedMembersRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/pharmacy-checkout': typeof AuthenticatedPharmacyCheckoutRoute
  '/pos': typeof AuthenticatedPosRoute
  '/production': typeof AuthenticatedProductionRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/purchasing': typeof AuthenticatedPurchasingRoute
  '/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/retainers': typeof AuthenticatedRetainersRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/time-tracking': typeof AuthenticatedTimeTrackingRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/contributions': typeof AuthenticatedContributionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/disbursements': typeof AuthenticatedDisbursementsRoute
  '/dispensary': typeof AuthenticatedDispensaryRoute
  '/donations': typeof AuthenticatedDonationsRoute
  '/eatery-inventory': typeof AuthenticatedEateryInventoryRoute
  '/eatery-reports': typeof AuthenticatedEateryReportsRoute
  '/eatery-sales': typeof AuthenticatedEaterySalesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/finished-goods': typeof AuthenticatedFinishedGoodsRoute
  '/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/members': typeof AuthenticatedMembersRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/pharmacy-checkout': typeof AuthenticatedPharmacyCheckoutRoute
  '/pos': typeof AuthenticatedPosRoute
  '/production': typeof AuthenticatedProductionRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/purchasing': typeof AuthenticatedPurchasingRoute
  '/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/retainers': typeof AuthenticatedRetainersRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/time-tracking': typeof AuthenticatedTimeTrackingRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/contributions': typeof AuthenticatedContributionsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/delivery': typeof AuthenticatedDeliveryRoute
  '/_authenticated/disbursements': typeof AuthenticatedDisbursementsRoute
  '/_authenticated/dispensary': typeof AuthenticatedDispensaryRoute
  '/_authenticated/donations': typeof AuthenticatedDonationsRoute
  '/_authenticated/eatery-inventory': typeof AuthenticatedEateryInventoryRoute
  '/_authenticated/eatery-reports': typeof AuthenticatedEateryReportsRoute
  '/_authenticated/eatery-sales': typeof AuthenticatedEaterySalesRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/finished-goods': typeof AuthenticatedFinishedGoodsRoute
  '/_authenticated/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/pharmacy-checkout': typeof AuthenticatedPharmacyCheckoutRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/_authenticated/purchasing': typeof AuthenticatedPurchasingRoute
  '/_authenticated/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/_authenticated/receipts': typeof AuthenticatedReceiptsRoute
  '/_authenticated/reconciliation': typeof AuthenticatedReconciliationRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/retainers': typeof AuthenticatedRetainersRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/time-tracking': typeof AuthenticatedTimeTrackingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/audit'
    | '/branches'
    | '/budget'
    | '/clients'
    | '/contributions'
    | '/customers'
    | '/delivery'
    | '/disbursements'
    | '/dispensary'
    | '/donations'
    | '/eatery-inventory'
    | '/eatery-reports'
    | '/eatery-sales'
    | '/expenses'
    | '/fees'
    | '/finished-goods'
    | '/housekeeping'
    | '/inventory'
    | '/invoices'
    | '/members'
    | '/menu'
    | '/orders'
    | '/patients'
    | '/payments'
    | '/payroll'
    | '/pharmacy-checkout'
    | '/pos'
    | '/production'
    | '/projects'
    | '/purchase-orders'
    | '/purchasing'
    | '/raw-materials'
    | '/receipts'
    | '/reconciliation'
    | '/reports'
    | '/reservations'
    | '/retainers'
    | '/rooms'
    | '/sales'
    | '/settings'
    | '/students'
    | '/time-tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/audit'
    | '/branches'
    | '/budget'
    | '/clients'
    | '/contributions'
    | '/customers'
    | '/delivery'
    | '/disbursements'
    | '/dispensary'
    | '/donations'
    | '/eatery-inventory'
    | '/eatery-reports'
    | '/eatery-sales'
    | '/expenses'
    | '/fees'
    | '/finished-goods'
    | '/housekeeping'
    | '/inventory'
    | '/invoices'
    | '/members'
    | '/menu'
    | '/orders'
    | '/patients'
    | '/payments'
    | '/payroll'
    | '/pharmacy-checkout'
    | '/pos'
    | '/production'
    | '/projects'
    | '/purchase-orders'
    | '/purchasing'
    | '/raw-materials'
    | '/receipts'
    | '/reconciliation'
    | '/reports'
    | '/reservations'
    | '/retainers'
    | '/rooms'
    | '/sales'
    | '/settings'
    | '/students'
    | '/time-tracking'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/audit'
    | '/_authenticated/branches'
    | '/_authenticated/budget'
    | '/_authenticated/clients'
    | '/_authenticated/contributions'
    | '/_authenticated/customers'
    | '/_authenticated/delivery'
    | '/_authenticated/disbursements'
    | '/_authenticated/dispensary'
    | '/_authenticated/donations'
    | '/_authenticated/eatery-inventory'
    | '/_authenticated/eatery-reports'
    | '/_authenticated/eatery-sales'
    | '/_authenticated/expenses'
    | '/_authenticated/fees'
    | '/_authenticated/finished-goods'
    | '/_authenticated/housekeeping'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/members'
    | '/_authenticated/menu'
    | '/_authenticated/orders'
    | '/_authenticated/patients'
    | '/_authenticated/payments'
    | '/_authenticated/payroll'
    | '/_authenticated/pharmacy-checkout'
    | '/_authenticated/pos'
    | '/_authenticated/production'
    | '/_authenticated/projects'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/purchasing'
    | '/_authenticated/raw-materials'
    | '/_authenticated/receipts'
    | '/_authenticated/reconciliation'
    | '/_authenticated/reports'
    | '/_authenticated/reservations'
    | '/_authenticated/retainers'
    | '/_authenticated/rooms'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/time-tracking'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contributions': {
      id: '/_authenticated/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof AuthenticatedContributionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/delivery': {
      id: '/_authenticated/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disbursements': {
      id: '/_authenticated/disbursements'
      path: '/disbursements'
      fullPath: '/disbursements'
      preLoaderRoute: typeof AuthenticatedDisbursementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispensary': {
      id: '/_authenticated/dispensary'
      path: '/dispensary'
      fullPath: '/dispensary'
      preLoaderRoute: typeof AuthenticatedDispensaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donations': {
      id: '/_authenticated/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof AuthenticatedDonationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eatery-inventory': {
      id: '/_authenticated/eatery-inventory'
      path: '/eatery-inventory'
      fullPath: '/eatery-inventory'
      preLoaderRoute: typeof AuthenticatedEateryInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eatery-reports': {
      id: '/_authenticated/eatery-reports'
      path: '/eatery-reports'
      fullPath: '/eatery-reports'
      preLoaderRoute: typeof AuthenticatedEateryReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eatery-sales': {
      id: '/_authenticated/eatery-sales'
      path: '/eatery-sales'
      fullPath: '/eatery-sales'
      preLoaderRoute: typeof AuthenticatedEaterySalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finished-goods': {
      id: '/_authenticated/finished-goods'
      path: '/finished-goods'
      fullPath: '/finished-goods'
      preLoaderRoute: typeof AuthenticatedFinishedGoodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/housekeeping': {
      id: '/_authenticated/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof AuthenticatedHousekeepingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy-checkout': {
      id: '/_authenticated/pharmacy-checkout'
      path: '/pharmacy-checkout'
      fullPath: '/pharmacy-checkout'
      preLoaderRoute: typeof AuthenticatedPharmacyCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchasing': {
      id: '/_authenticated/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof AuthenticatedPurchasingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/raw-materials': {
      id: '/_authenticated/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof AuthenticatedRawMaterialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipts': {
      id: '/_authenticated/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reconciliation': {
      id: '/_authenticated/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthenticatedReconciliationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/retainers': {
      id: '/_authenticated/retainers'
      path: '/retainers'
      fullPath: '/retainers'
      preLoaderRoute: typeof AuthenticatedRetainersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/time-tracking': {
      id: '/_authenticated/time-tracking'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof AuthenticatedTimeTrackingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedContributionsRoute: typeof AuthenticatedContributionsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDeliveryRoute: typeof AuthenticatedDeliveryRoute
  AuthenticatedDisbursementsRoute: typeof AuthenticatedDisbursementsRoute
  AuthenticatedDispensaryRoute: typeof AuthenticatedDispensaryRoute
  AuthenticatedDonationsRoute: typeof AuthenticatedDonationsRoute
  AuthenticatedEateryInventoryRoute: typeof AuthenticatedEateryInventoryRoute
  AuthenticatedEateryReportsRoute: typeof AuthenticatedEateryReportsRoute
  AuthenticatedEaterySalesRoute: typeof AuthenticatedEaterySalesRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedFinishedGoodsRoute: typeof AuthenticatedFinishedGoodsRoute
  AuthenticatedHousekeepingRoute: typeof AuthenticatedHousekeepingRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPharmacyCheckoutRoute: typeof AuthenticatedPharmacyCheckoutRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRoute
  AuthenticatedPurchasingRoute: typeof AuthenticatedPurchasingRoute
  AuthenticatedRawMaterialsRoute: typeof AuthenticatedRawMaterialsRoute
  AuthenticatedReceiptsRoute: typeof AuthenticatedReceiptsRoute
  AuthenticatedReconciliationRoute: typeof AuthenticatedReconciliationRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedRetainersRoute: typeof AuthenticatedRetainersRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTimeTrackingRoute: typeof AuthenticatedTimeTrackingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedContributionsRoute: AuthenticatedContributionsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDeliveryRoute: AuthenticatedDeliveryRoute,
  AuthenticatedDisbursementsRoute: AuthenticatedDisbursementsRoute,
  AuthenticatedDispensaryRoute: AuthenticatedDispensaryRoute,
  AuthenticatedDonationsRoute: AuthenticatedDonationsRoute,
  AuthenticatedEateryInventoryRoute: AuthenticatedEateryInventoryRoute,
  AuthenticatedEateryReportsRoute: AuthenticatedEateryReportsRoute,
  AuthenticatedEaterySalesRoute: AuthenticatedEaterySalesRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedFinishedGoodsRoute: AuthenticatedFinishedGoodsRoute,
  AuthenticatedHousekeepingRoute: AuthenticatedHousekeepingRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPharmacyCheckoutRoute: AuthenticatedPharmacyCheckoutRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedPurchaseOrdersRoute: AuthenticatedPurchaseOrdersRoute,
  AuthenticatedPurchasingRoute: AuthenticatedPurchasingRoute,
  AuthenticatedRawMaterialsRoute: AuthenticatedRawMaterialsRoute,
  AuthenticatedReceiptsRoute: AuthenticatedReceiptsRoute,
  AuthenticatedReconciliationRoute: AuthenticatedReconciliationRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedRetainersRoute: AuthenticatedRetainersRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTimeTrackingRoute: AuthenticatedTimeTrackingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
